# Generated by Django 5.2 on 2025-05-13 17:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='address',
            field=models.TextField(default='Unknown Address'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='application',
            name='has_alarm',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='application',
            name='has_tracking_device',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='application',
            name='mileage',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='application',
            name='modifications',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='parking_type',
            field=models.CharField(choices=[('garage', 'Garage'), ('street', 'Street'), ('secure_lot', 'Secure Lot')], default='street', max_length=50),
        ),
        migrations.AddField(
            model_name='application',
            name='registration_number',
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='application',
            name='vin',
            field=models.CharField(default=0, max_length=17),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quote',
            name='address',
            field=models.TextField(default='Unknown Address', max_length=255),
        ),
        migrations.AddField(
            model_name='quote',
            name='has_alarm',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='quote',
            name='has_tracking_device',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='quote',
            name='parking_type',
            field=models.CharField(choices=[('garage', 'Garage'), ('street', 'Street'), ('secure_lot', 'Secure Lot')], default='street', max_length=50),
        ),
        migrations.AddField(
            model_name='quote',
            name='risk_factors',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='claims_history',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='driving_experience_years',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='emergency_contact',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='license_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='proof_of_income',
            field=models.FileField(blank=True, null=True, upload_to='income_proofs/'),
        ),
        migrations.CreateModel(
            name='Policy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('policy_type', models.CharField(choices=[('third_party', 'Third-Party'), ('third_party_fire_theft', 'Third-Party, Fire & Theft'), ('comprehensive', 'Comprehensive')], max_length=50)),
                ('premium', models.DecimalField(decimal_places=2, max_digits=10)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('status', models.CharField(choices=[('active', 'Active'), ('expired', 'Expired'), ('cancelled', 'Cancelled')], default='active', max_length=20)),
                ('payment_status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('application', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='insurance.application')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='claim',
            name='policy',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='insurance.policy'),
        ),
    ]
